let inpu1 = document.getElementById('inpu1') 
let inpu  = document.getElementById('inpu') 
let inpu2 = document.getElementById('inpu2') 
let result = document.getElementById('result') 
let alam1 =document.getElementById('alam1')
let alam2 =document.getElementById('alam2')
let alam3 =document.getElementById('alam3')
let alam4 =document.getElementById('alam4')
